Develop
RomanBatrakov/java-explore-with-me pull request #2
Opened 2023-01-03 20:24 UTC by RomanBatrakov

2023-01-05 21:33 UTC, alexache requested changes

2023-01-05 21:33 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/ewm/category/service/CategoryServiceImpl.java
> +            int size = eventService.getAllEventsByFilter(null, null, Collections.singletonList(id),
Немного не понятно, зачем так сложно? Почему не existsById?

2023-01-05 21:33 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/ewm/event/mapper/EventMapper.java
> +    List<EventDto> toEvenDtoList(List<Event> events);
Опечатка

2023-01-05 21:33 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/ewm/event/model/Event.java
> +    private Long views;
Это нуэно не хранить в базе, а получать у сервиса статистики

2023-01-05 21:33 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/ewm/event/model/Event.java
> +    private Long confirmedRequests;
Это излишне хранить в базе, можно получать запросом к таблице запросов

2023-01-05 21:33 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/ewm/event/service/EventServiceImpl.java
> +            event.setViews(event.getViews() + 1);
Это очень ненадежный и тем опасный способ. Что если придет несколько запросов, какой из них сохранится? Для отслеживания этого есть сервис статистики

2023-01-05 21:33 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/ewm/event/service/EventServiceImpl.java
> +        List<Event> events = (predicate == null) ? eventRepository.findAll(pageable).getContent()
Использование views, confirmedRequests из этой табличцы - это не очень хороший хак, нужно сделать полноценный запрос к сервису статистики и запрос получеенич количества подтвержденных заявок в таблицу заявок (нуэно еще избегать запроса к базе в цикле)

2023-01-05 21:33 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/ewm/hit/client/HitClient.java
> +@RestController
Почему это контроллер?

2023-01-05 21:33 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/ewm/hit/client/HitClient.java
> +    public void postHit(Hit hit) throws WebClientRequestException {
Отправка статистики - это полдела, нужно еще ее получать

2023-01-05 21:33 UTC, alexache commented on stats-server/pom.xml
> +            <version>${postgreSQL.version}</version>
Версии желательно указывать в родительском модуле через dependencyManagement

2023-01-06 17:09 UTC, RomanBatrakov commented on ewm-service/src/main/java/ru/practicum/ewm/category/controller/AdminCategoryController.java
> +    public ResponseEntity<Object> deleteCategory(@PathVariable("catId") Long id) {
Мне показалось, что это более гибкое решение, которое позволяет, например, в DELETE методах возвращать статус ОК. И чтобы был единообразие, я везде сделал так.

2023-01-06 17:28 UTC, RomanBatrakov commented on ewm-service/src/main/java/ru/practicum/ewm/category/controller/AdminCategoryController.java
> +    public ResponseEntity<Object> deleteCategory(@PathVariable("catId") Long id) {
Или будет корректнее в DELETE методах ничего не возвращать и убрать ResponseEntity?

2023-01-06 17:29 UTC, RomanBatrakov commented on ewm-service/src/main/java/ru/practicum/ewm/category/service/CategoryServiceImpl.java
> +            int size = eventService.getAllEventsByFilter(null, null, Collections.singletonList(id),
У нас по ТЗ есть условие, что у удаляемой категории не должно быть событий. Чтобы не создавать одельных методов, я воспользовался готовым. Или лучше отдельный метод для проверки написать?

2023-01-07 16:47 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/ewm/category/controller/AdminCategoryController.java
> +    public ResponseEntity<Object> deleteCategory(@PathVariable("catId") Long id) {
Я про все методы контроллеров в целом - ResponseEntity лишние

2023-01-07 16:50 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/ewm/category/service/CategoryServiceImpl.java
> +            int size = eventService.getAllEventsByFilter(null, null, Collections.singletonList(id),
Я бы скорее предложил использовать что-то вроде eventRepository.existsByCategoryName()

2023-01-11 00:28 UTC, alexache approved these changes

2023-01-11 06:42 UTC, merged